namespace Fima.Data
{
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using Models;

    public class ApplicationDbContext : IdentityDbContext<FimaUser, FimaRole, int, FimaLogin, FimaUserRole, FimaClaim>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // map to columns
            modelBuilder.Entity<FimaUser>().ToTable("FimaUsers", "dbo");
            modelBuilder.Entity<FimaRole>().ToTable("FimaRoles", "dbo");
            modelBuilder.Entity<FimaUserRole>().ToTable("FimaUserRoles", "dbo");
            modelBuilder.Entity<FimaClaim>().ToTable("FimaClaims", "dbo");
            modelBuilder.Entity<FimaLogin>().ToTable("FimaLogins", "dbo");

            // autogenerated id
            modelBuilder.Entity<FimaUser>().Property(r => r.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            modelBuilder.Entity<FimaRole>().Property(r => r.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            modelBuilder.Entity<FimaClaim>().Property(r => r.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        }
    }
}
