
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BANK_ACCOUNT_TYPES
{

    public string BANK_ACCOUNT_TYPE { get; set; }

}

}
