
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BANK_ACCOUNTS
{

    public string IBAN { get; set; }

    public string ACCOUNT_TYPE { get; set; }

    public string WITH_BANK { get; set; }

    public string ACCOUNT_CURRENCY { get; set; }

    public string FUND_ID { get; set; }

    public Nullable<double> INT_ACCRUED { get; set; }

    public string ACCRUE_INTEREST { get; set; }

    public Nullable<double> ACCOUNT_NUMBER { get; set; }

}

}
