
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BETA_CALC
{

    public string tck { get; set; }

    public Nullable<double> bsp { get; set; }

    public Nullable<double> bdj { get; set; }

    public Nullable<double> b1 { get; set; }

    public string beta_fund { get; set; }

}

}
