
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BIGACCOUNTINGTABLE_PERIOD_FSUM
{

    public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }

    public Nullable<double> FCT_ACC { get; set; }

    public Nullable<double> FCT_SUMBGN2 { get; set; }

    public Nullable<double> FDT_ACC { get; set; }

    public Nullable<double> FDT_SUMBGN2 { get; set; }

    public Nullable<double> NEW_ACC { get; set; }

    public Nullable<double> NEW_SUMBGN { get; set; }

    public string NEW_ACC_GROUP { get; set; }

    public string TRANSACTION_FUNDID { get; set; }

    public string TRANSACTION_DT_CT { get; set; }

}

}
