
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BIGACCOUNTINGTABLE_PERIOD_FDT
{

    public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }

    public double FDT_ID { get; set; }

    public string TRANSACTION_DT_CT { get; set; }

    public double FDT_ACC { get; set; }

    public Nullable<double> FDT_SUMBGN { get; set; }

    public string TRANSACTION_FUNDID { get; set; }

    public int TRANSACTION_INT { get; set; }

}

}
