//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BULLETIN_USA
    {
        public System.DateTime USA_DATE { get; set; }
        public string USA_POSITION { get; set; }
        public string USA_CCY { get; set; }
        public Nullable<double> USA_LASTPRICE { get; set; }
        public Nullable<double> USA_LASTPRICE_ADJ { get; set; }
        public Nullable<double> USA_QUANTITY_TRADES { get; set; }
        public Nullable<double> USA_OPEN { get; set; }
        public Nullable<double> USA_HIGH { get; set; }
        public Nullable<double> USA_LOW { get; set; }
        public Nullable<double> BEST_BID { get; set; }
        public Nullable<double> BEST_ASK { get; set; }
        public Nullable<double> OTHER_PRICE { get; set; }
        public string DES_OTHER_PRICE { get; set; }
        public Nullable<int> INDEX { get; set; }
        public string FUND { get; set; }
    }
}
