//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contracts_schroders
    {
        public int contract_sch_id { get; set; }
        public Nullable<System.DateTime> contract_sch_date { get; set; }
        public string contract_sch_time { get; set; }
        public string contract_sch_place { get; set; }
        public string contract_sch_client { get; set; }
        public string contract_sch_iban { get; set; }
        public string contract_sch_bank { get; set; }
        public string contract_sch_pylnom1 { get; set; }
        public string contract_sch_pylnom2 { get; set; }
        public string contract_sch_crby { get; set; }
        public string contract_sch_crwhen { get; set; }
        public string contract_sch_modby { get; set; }
        public string contract_sch_modwhen { get; set; }
        public string contract_sch_biccode { get; set; }
    }
}
