
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class contracts_kcm_readable
{

    public int contract_kcm_id { get; set; }

    public Nullable<System.DateTime> contract_kcm_date { get; set; }

    public string contract_kcm_time { get; set; }

    public string contract_kcm_place { get; set; }

    public string contract_kcm_client { get; set; }

    public string contract_kcm_iban { get; set; }

    public string contract_kcm_bank { get; set; }

    public Nullable<int> CLIENTID { get; set; }

    public string clientegn { get; set; }

    public string clientstring { get; set; }

    public string clientname { get; set; }

    public string clientiddoc { get; set; }

    public string clientiddate { get; set; }

    public string clientperson { get; set; }

    public string clientidissueby { get; set; }

    public string clientcountry { get; set; }

    public string clienttown { get; set; }

    public string clientaddress { get; set; }

    public string clienttel { get; set; }

    public string clientgsm { get; set; }

    public string clientemail { get; set; }

    public string pylnom1egn { get; set; }

    public string pylnom1id { get; set; }

    public string pylnom1iddate { get; set; }

    public string pylnomid1issuedby { get; set; }

    public string pylnom1tel { get; set; }

    public string pylnom1gsm { get; set; }

    public string pylnom2egn { get; set; }

    public string pylnom2id { get; set; }

    public string pylnom2iddate { get; set; }

    public string pylnom2issuedby { get; set; }

    public string pylnom2tel { get; set; }

    public string pylnom2gsm { get; set; }

    public string pylnom1name { get; set; }

    public string pylnom2name { get; set; }

    public string contract_kcm_crby { get; set; }

}

}
