
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRACTED_PARTIES
{

    public string CP_ID { get; set; }

    public string CP_NAME { get; set; }

    public string CP_DES { get; set; }

    public string CP_CCY { get; set; }

    public string CP_TYPE { get; set; }

}

}
