
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class COUNTRIES
{

    public string COUNTRY { get; set; }

    public string ISO_CODE { get; set; }

    public string COUNTRY_DES { get; set; }

    public string COUNTRY_ENG { get; set; }

}

}
