
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DATAUD_AVRORA
{

    public string BULSTATUD { get; set; }

    public string NAMEUD { get; set; }

    public string ADDRESS_REGISTRATION { get; set; }

    public string COURT_REGISTRATION { get; set; }

    public string BOARDDIRECTOR_MEMBER { get; set; }

    public string BOARDDIRECTOR_MEMBER2 { get; set; }

    public string BOARDDIRECTOR_MEMBER3 { get; set; }

    public string BOARDDIRECTOR_MEMBER4 { get; set; }

    public string LICENCE_UD { get; set; }

    public string GLOBALID_CD { get; set; }

    public string MOL { get; set; }

}

}
