//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_BIGACCOUNTINGTABLE_SUMMARYPORTFOLIO_SCH
    {
        public string TRANSACTION_ISIN { get; set; }
        public double GLOBAL_ID { get; set; }
        public double TRANSACTION_ID { get; set; }
        public int TRANSACTION_INT { get; set; }
        public string TRANSACTION_FOLDER { get; set; }
        public string TRANSACTION_DES { get; set; }
        public string TRANSACTION_DES2 { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DOC_DATE { get; set; }
        public string TRANSACTION_CCY { get; set; }
        public string TRANSACTION_DT_CT { get; set; }
        public double TRANSACTION_ACCOUNT { get; set; }
        public Nullable<short> CODE { get; set; }
        public Nullable<double> TRANSACTION_QUANTITY { get; set; }
        public Nullable<double> TYRANSACTION_SUMCCY { get; set; }
        public Nullable<double> TRANSACTION_SP { get; set; }
        public Nullable<double> TRANSACTION_FX { get; set; }
        public Nullable<double> TRANSACTION_SPBGN { get; set; }
        public Nullable<double> TRANSACTION_SUMBGN { get; set; }
        public string TRANSACTION_STATUS { get; set; }
        public string TRANSACTION_FUNDID { get; set; }
    }
}
