//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSIT_CONVENTIONS
    {
        public int CONV_ID { get; set; }
        public string DEPOSIT_CONVENTION { get; set; }
        public Nullable<short> DAYS { get; set; }
        public Nullable<int> DAYS_SMALL { get; set; }
    }
}
