//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORWARD_CONTRACTS_ALLFUNDS
    {
        public double FRD_ID { get; set; }
        public Nullable<System.DateTime> FRD_DATE { get; set; }
        public Nullable<System.DateTime> FRD_MATURITY { get; set; }
        public string FRD_BUY_CCY { get; set; }
        public Nullable<double> FRD_BUY_AMOUNT { get; set; }
        public string FRD_SELL_CCY { get; set; }
        public Nullable<double> FRD_SELL_AMOUNT { get; set; }
        public string FUND_ID { get; set; }
        public string STATUS { get; set; }
    }
}
