
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GENERAL_LEDGER
{

    public Nullable<int> MASTER_NUMBER { get; set; }

    public string MASTER_NAME { get; set; }

    public short GROUP_NUMBER { get; set; }

    public string GROUP_NAME { get; set; }

    public double ACCOUNT_NUMBER { get; set; }

    public string ACCOUNT_NAME { get; set; }

    public string ACC_CURRENCY { get; set; }

    public string ACCOUNT_TYPE { get; set; }

    public string DESCRIPTION { get; set; }

    public string REVALUATION { get; set; }

    public string RAZCHET { get; set; }

    public Nullable<short> CODE { get; set; }

    public Nullable<int> REVAL_DECIMALS { get; set; }

}

}
