//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTORS_FUNDS_HIST
    {
        public int CLIENTID { get; set; }
        public string CLIENTID_STRING { get; set; }
        public string PERSONALID_BULSTAT { get; set; }
        public int CONTRACT_TYPE { get; set; }
        public string TYPE_PERSON { get; set; }
        public string TYPE_ORGANIZATION { get; set; }
        public string FIRSTNAME { get; set; }
        public string SECONDNAME { get; set; }
        public string LASTNAME { get; set; }
        public string FULL_NAME { get; set; }
        public string PERSONAL_ID { get; set; }
        public string PERSONAL_ID_DATE { get; set; }
        public string PERSONAL_ID_ISSUED_BY { get; set; }
        public string COUNTRY_ADDRESS_ID { get; set; }
        public string TOWN_ADDRESS_ID { get; set; }
        public string ADDRESS_ID { get; set; }
        public string E_MAIL { get; set; }
        public string TEL_FIXED { get; set; }
        public string TEL_MOBILE { get; set; }
        public string AUTHORISED_TYPE { get; set; }
        public string AUTHORISED_NAME { get; set; }
        public string AUTHORISED_DOC { get; set; }
        public string AUTHORISED_DATE { get; set; }
        public string AUTHORISED_TYPE2 { get; set; }
        public string AUTHORISED_NAME2 { get; set; }
        public string AUTHORISED_DATE2 { get; set; }
        public string DDS_REGISTERED { get; set; }
        public string ID_NUMBER_TAX_ID { get; set; }
        public string EMPLOYEE_AUTHORISED { get; set; }
        public string CLIENT_BIRTHDATE { get; set; }
        public string IBAN1 { get; set; }
        public string BIC1 { get; set; }
        public string BANK1 { get; set; }
        public string IBAN2 { get; set; }
        public string BIC2 { get; set; }
        public string BANK2 { get; set; }
        public string IBAN3 { get; set; }
        public string BIC3 { get; set; }
        public string BANK3 { get; set; }
        public string AUTH_NOTARY { get; set; }
        public string AUTH_NOTARY2 { get; set; }
        public string AUTHORISED_DOC2 { get; set; }
        public string CL_STATUS { get; set; }
        public Nullable<int> CD_GLOBID { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public string CREATED_WHEN { get; set; }
        public string CD_REG { get; set; }
        public string user_modified { get; set; }
        public string user_modified_time { get; set; }
        public string CD_BIC { get; set; }
        public string MUNICIPALITY { get; set; }
        public string RESIDENCE { get; set; }
        public string STREET { get; set; }
        public string STRNUM { get; set; }
        public string FLOOR1 { get; set; }
        public string FLAT { get; set; }
        public string COUNTRY1 { get; set; }
        public string TOWN1 { get; set; }
        public string COUNTRY2 { get; set; }
        public string TOWN2 { get; set; }
        public string DCITIZENS { get; set; }
        public string IBAN_CD_AI { get; set; }
        public string IBAN_CD_AEE { get; set; }
        public string IBAN_CD_AEEO { get; set; }
        public string IBAN_CD_AGT { get; set; }
        public string IBAN_CD_ACF { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string USER_ID { get; set; }
        public string ACT_EVENT { get; set; }
    }
}
