//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTORS_AUTH
    {
        public int AUTH_CLID { get; set; }
        public string AUTH_CLID_STRING { get; set; }
        public string AUTH_PERSONAL_ID { get; set; }
        public string AUTH_FULLNAME { get; set; }
        public string AUTH_PID { get; set; }
        public string AUTH_COUNTRY { get; set; }
        public string AUTH_TOWN { get; set; }
        public string AUTH_ADDRESS { get; set; }
        public string AUTH_TYPE { get; set; }
        public string AUTH_DOC1 { get; set; }
        public string AUTH_DATE1 { get; set; }
        public string AUTH_PID_ISSUEDBY { get; set; }
        public string AUTH_PID_DATE { get; set; }
        public string AUTH_NOTARY { get; set; }
        public string AUTH_TEL_MOBILE { get; set; }
        public string AUTH_EMAIL { get; set; }
    }
}
