
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class INVESTMENT_TYPES
{

    public string INVESTMENT_TYPE { get; set; }

    public string INVESTMENT_TYPE_BG { get; set; }

    public int type_id { get; set; }

}

}
