//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAX_DATE_REVAL_SCH
    {
        public Nullable<System.DateTime> MAX_DATE { get; set; }
        public string MAX_FOLDER { get; set; }
        public string fund { get; set; }
    }
}
