//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAV_CALCULATION_ALLFUNDS
    {
        public System.DateTime DATE_NAV { get; set; }
        public string DATE_NAV_ID { get; set; }
        public string DATE_NAV_NAME { get; set; }
        public Nullable<double> DATE_NAV_ACCOUNT { get; set; }
        public string DATE_NAV_CCY { get; set; }
        public Nullable<double> DATE_NAV_QUANT { get; set; }
        public Nullable<double> DATE_NAV_AMCCY { get; set; }
        public Nullable<double> DATE_NAV_SP { get; set; }
        public Nullable<double> DATE_NAV_FX { get; set; }
        public Nullable<double> DATE_NAV_SPBGN { get; set; }
        public string DATE_NAV_FUNDID { get; set; }
        public string DATE_NAV_STATUS { get; set; }
    }
}
