//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_BANKS
    {
        public string BANK_NAME { get; set; }
        public string BANK_BIC { get; set; }
        public string KEY_BIC { get; set; }
    }
}
