
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PORTFOLIO_DEALS_HIST
{

    public double PORT_DEAL_ID { get; set; }

    public string PORT_DEAL_ID_STRING { get; set; }

    public Nullable<double> BFB_ID { get; set; }

    public Nullable<double> PORT_DEALORD_ID { get; set; }

    public string BFB_ORD_ID { get; set; }

    public string PORT_DEAL_FUND { get; set; }

    public Nullable<System.DateTime> PORT_DEAL_TRADEDATE { get; set; }

    public Nullable<System.DateTime> PORT_DEAL_SETTLDATE { get; set; }

    public string PORT_DEAL_INV { get; set; }

    public string PORT_DEAL_INV_NAME { get; set; }

    public string PORT_DEAL_CCY { get; set; }

    public string PORT_DEAL_TYPE { get; set; }

    public Nullable<double> PORT_DEAL_QUANT { get; set; }

    public Nullable<double> PORT_DEAL_PRICE { get; set; }

    public Nullable<double> PER_NOMINAL { get; set; }

    public Nullable<double> OTHERCOMMISSION { get; set; }

    public Nullable<double> BROKERCOMMISSION { get; set; }

    public Nullable<double> BROKERCOMMISSION2 { get; set; }

    public Nullable<double> PORT_DEAL_AMOUNT { get; set; }

    public Nullable<double> PORT_DEAL_AMOUNT_BGN { get; set; }

    public string PORT_DEAL_BROKER { get; set; }

    public string PORT_DEAL_BROKER_ID { get; set; }

    public string PORT_DEAL_FUND1 { get; set; }

    public string PORT_DEAL_BROKER1 { get; set; }

    public string PORT_DEAL_BROKER1_ID { get; set; }

    public Nullable<double> PORT_DEAL_FX { get; set; }

    public Nullable<double> AVERAGE_PRICE { get; set; }

    public Nullable<double> AVERAGE_PRICE_BGN { get; set; }

    public string PORT_DEAL_PLACE { get; set; }

    public Nullable<int> POSITION_PARTIDA { get; set; }

    public Nullable<System.DateTime> PORT_DEAL_ACTUALSETTLDATE { get; set; }

    public string CONFIRMATION { get; set; }

    public string PORTFOLIO_DOCUMENT { get; set; }

    public string EMPLOYEE { get; set; }

    public string PORT_DEAL_TIME { get; set; }

    public string SETTL_INSTR { get; set; }

    public Nullable<int> IP_TR_ID { get; set; }

    public Nullable<System.DateTime> REC_DATE { get; set; }

    public Nullable<System.DateTime> EX_DATE { get; set; }

    public string DOC_PATH { get; set; }

    public string OLD_ID { get; set; }

    public string CCY_PMNT { get; set; }

    public Nullable<double> AMOUNT_PMNT { get; set; }

    public string STATUS_PMNT { get; set; }

    public string user_modified { get; set; }

    public string user_modified_time { get; set; }

    public string COMMENT { get; set; }

    public Nullable<double> PORT_DEAL_QUANT_1 { get; set; }

    public Nullable<System.DateTime> MEETING_DATE { get; set; }

    public Nullable<System.DateTime> ACC_DATE { get; set; }

    public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }

    public string USER_ID { get; set; }

    public string ACT_EVENT { get; set; }

}

}
