//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTFOLIO_ORDERS_HIST
    {
        public Nullable<System.DateTime> PORT_ORD_DATE { get; set; }
        public string PORT_ORD_TIME { get; set; }
        public double PORT_ORD_ID { get; set; }
        public Nullable<double> PORT_ORD_ID_STRING { get; set; }
        public string PORT_ORD_FUND { get; set; }
        public string INVESTMENT { get; set; }
        public string INVESTMENT_NAME { get; set; }
        public string PORT_ORD_TYPE { get; set; }
        public string ORD_TYPE_PRICE { get; set; }
        public string PORT_ORD_BROKER { get; set; }
        public Nullable<double> PORT_ORD_AMOUNT { get; set; }
        public Nullable<double> PORT_ORD_PRICE { get; set; }
        public Nullable<double> PORT_ORD_QUANTITY { get; set; }
        public string PORT_ORD_PLACE { get; set; }
        public string PORT_ORD_OPERATION { get; set; }
        public string EMPLOYEE { get; set; }
        public string VALIDITY { get; set; }
        public string MARKET { get; set; }
        public string BFB_ID { get; set; }
        public string DOCUMENT { get; set; }
        public string OLD_ID { get; set; }
        public string STATUS { get; set; }
        public string user_modified { get; set; }
        public string user_modified_time { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string USER_ID { get; set; }
        public string ACT_EVENT { get; set; }
    }
}
