//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_INVESTMENTS_BONDS_ONLY
    {
        public string ISIN { get; set; }
        public string CURRENCY { get; set; }
        public string TYPE { get; set; }
        public string TICKER1 { get; set; }
        public string TICKER2 { get; set; }
        public string NAME_BG { get; set; }
        public Nullable<System.DateTime> LAST_INT_PMNT { get; set; }
        public Nullable<double> PAR_AMOUNT { get; set; }
        public string CONVENTION { get; set; }
        public Nullable<double> CONV_DAYS_BIG { get; set; }
        public Nullable<double> CONV_DAYS_SMALL { get; set; }
        public Nullable<double> INT_RATE { get; set; }
    }
}
