//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITIONS_INVESTMENTS
    {
        public string ISIN { get; set; }
        public string TICKER1 { get; set; }
        public string TICKER2 { get; set; }
        public string CURRENCY { get; set; }
        public string TYPE { get; set; }
        public string COUNTRY { get; set; }
        public string NAME_BG { get; set; }
        public string NAME_ENG { get; set; }
        public string PRIMARYMARKET { get; set; }
        public string MARKETSEGMENT { get; set; }
        public string SECTOR_BG { get; set; }
        public string SECTOR_ENG { get; set; }
        public string SHORT_LONG { get; set; }
        public Nullable<int> RATIO { get; set; }
        public Nullable<int> SECTOR_BNB { get; set; }
        public string MARKET_BNB { get; set; }
        public string COUNTRY_BNB { get; set; }
        public string CCY_BNB { get; set; }
        public Nullable<double> NUMBERSHARES_OUT { get; set; }
        public string TYPE_BNB { get; set; }
        public string INDEXBETA { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public Nullable<System.DateTime> LAST_INT_PMNT { get; set; }
        public Nullable<System.DateTime> NEXT_INT_PMNT { get; set; }
        public Nullable<double> PAR_AMOUNT { get; set; }
        public string CONVENTION { get; set; }
        public Nullable<double> CONV_DAYS_BIG { get; set; }
        public Nullable<double> CONV_DAYS_SMALL { get; set; }
        public Nullable<double> INT_RATE { get; set; }
        public string user_modified { get; set; }
        public string user_modified_time { get; set; }
        public string issuer_id { get; set; }
    }
}
