//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_BONDS_INTEREST_1
    {
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string TRANSACTION_ISIN { get; set; }
        public double TRANSACTION_ACCOUNT { get; set; }
        public string TRANSACTION_CCY { get; set; }
        public Nullable<double> TRANSACTION_QUANTITY { get; set; }
        public Nullable<double> TYRANSACTION_SUMCCY { get; set; }
        public Nullable<double> TRANSACTION_SUMBGN { get; set; }
    }
}
