//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_orders_active
    {
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string INVESTOR { get; set; }
        public string INVESTOR_ID { get; set; }
        public string ORDER_CURRENCY { get; set; }
        public string ORDER_FUND { get; set; }
        public Nullable<double> ORDER_SHARES { get; set; }
        public Nullable<double> ORDER_SUM { get; set; }
        public string STATUS { get; set; }
        public string ORDER_TYPE { get; set; }
        public double ORDER_ID { get; set; }
        public Nullable<double> ORDER_ID_STRING { get; set; }
        public string ordertime { get; set; }
        public Nullable<double> order_entry_fee_sum { get; set; }
        public Nullable<double> ORDER_SUM_NET { get; set; }
        public string DEALS_TYPE { get; set; }
        public string DEALS_CURRENCY { get; set; }
    }
}
