
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TEST_CD_MESSAGES
{

    public int CD_GID { get; set; }

    public string CD_TIME { get; set; }

    public Nullable<System.DateTime> CD_DATE { get; set; }

    public string CD_MESSAGE_NUMBER { get; set; }

    public string CORR_MESSAGE_NUMBER { get; set; }

    public Nullable<double> CD_MT_number { get; set; }

    public string CD_MESSAGE_ID { get; set; }

    public string CD_MESSAGE_TRID { get; set; }

    public string CD_MESSAGE_TYPE { get; set; }

    public string CD_FOLDER { get; set; }

    public string CD_MESSAGE_DES { get; set; }

    public string CD_MESSAGE_DES2 { get; set; }

    public string CD_MESSAGE_PATH { get; set; }

    public string CD_MESSAGE_FUNDID { get; set; }

    public string CD_ACTION_TYPE { get; set; }

    public string CD_CONFIRMATION { get; set; }

    public string CD_STATUS { get; set; }

    public string CD_MESSAGE_TEXT { get; set; }

    public string CD_ANSWER_RESULT { get; set; }

    public string CD_EGN_BULSTAT { get; set; }

    public string CD_FULLNAME { get; set; }

    public string CD_FUNDID { get; set; }

}

}
