
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UNMATCHED_ACCOUNT_MESSAGES
{

    public Nullable<int> CLIENTID { get; set; }

    public string FORMATED_ID { get; set; }

    public string CLIENTID_STRING { get; set; }

    public string INVESTOR_ID { get; set; }

    public string FULL_NAME { get; set; }

    public string TYPE_PERSON { get; set; }

    public string TYPE_ORGANIZATION { get; set; }

    public string ORDER_FUND { get; set; }

    public string FUNDNAME { get; set; }

    public string ISINCODE { get; set; }

    public string FIRSTNAME { get; set; }

    public string SECONDNAME { get; set; }

    public string LASTNAME { get; set; }

    public string STATUS { get; set; }

}

}
