//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNMATCHED_CD_REGISTER_TRANSACTIONS
    {
        public double DEALS_ID { get; set; }
        public string DEALS_INVESTOR { get; set; }
        public string CLIENTID_STRING { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<System.DateTime> DATE_DEAL { get; set; }
        public string DEALS_TYPE { get; set; }
        public Nullable<double> DEALS_SHARES { get; set; }
        public string DEALS_FUND { get; set; }
        public string ISINCODE { get; set; }
        public string ACCOUNT_WITH_CD { get; set; }
        public string STATUS { get; set; }
    }
}
