//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROKERS
    {
        public int BROKER_INT { get; set; }
        public string BROKERNAME { get; set; }
        public string BROKERID { get; set; }
        public string BROKER_ISIN { get; set; }
    }
}
