//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KpEntities : DbContext
    {
        public KpEntities()
            : base("name=KpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANK_ACCOUNT_TYPES> BANK_ACCOUNT_TYPES { get; set; }
        public virtual DbSet<BANK_ACCOUNTS> BANK_ACCOUNTS { get; set; }
        public virtual DbSet<BANKS> BANKS { get; set; }
        public virtual DbSet<BIG_ACCOUNTING_TABLE> BIG_ACCOUNTING_TABLE { get; set; }
        public virtual DbSet<BIG_ACCOUNTING_TABLE_kur> BIG_ACCOUNTING_TABLE_kur { get; set; }
        public virtual DbSet<BIG_ACCOUNTING_TABLE_SCH> BIG_ACCOUNTING_TABLE_SCH { get; set; }
        public virtual DbSet<BNB_CCY> BNB_CCY { get; set; }
        public virtual DbSet<BNB_COUNTRY> BNB_COUNTRY { get; set; }
        public virtual DbSet<BNB_MARKETS> BNB_MARKETS { get; set; }
        public virtual DbSet<BNB_SECTOR> BNB_SECTOR { get; set; }
        public virtual DbSet<BNB_TYPE> BNB_TYPE { get; set; }
        public virtual DbSet<BRANCH_BG> BRANCH_BG { get; set; }
        public virtual DbSet<BROKERS> BROKERS { get; set; }
        public virtual DbSet<BULLETIN_BFB> BULLETIN_BFB { get; set; }
        public virtual DbSet<BULLETIN_USA> BULLETIN_USA { get; set; }
        public virtual DbSet<CALENDAR> CALENDAR { get; set; }
        public virtual DbSet<CD_MESSAGES> CD_MESSAGES { get; set; }
        public virtual DbSet<CD_TEXT_MESSAGES> CD_TEXT_MESSAGES { get; set; }
        public virtual DbSet<CE_EVENT_TYPES> CE_EVENT_TYPES { get; set; }
        public virtual DbSet<CONTRACTED_PARTIES> CONTRACTED_PARTIES { get; set; }
        public virtual DbSet<CONTRACTS> CONTRACTS { get; set; }
        public virtual DbSet<contracts_kcm> contracts_kcm { get; set; }
        public virtual DbSet<contracts_schroders> contracts_schroders { get; set; }
        public virtual DbSet<CORPORATE_EVENTS_ALLFUNDS> CORPORATE_EVENTS_ALLFUNDS { get; set; }
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<CURRENCIES> CURRENCIES { get; set; }
        public virtual DbSet<DAILYPRICES> DAILYPRICES { get; set; }
        public virtual DbSet<DATAUD_AVRORA> DATAUD_AVRORA { get; set; }
        public virtual DbSet<DEFERRED_EXPENSES_COUNTERPARTIES> DEFERRED_EXPENSES_COUNTERPARTIES { get; set; }
        public virtual DbSet<DEPOSIT_CONVENTIONS> DEPOSIT_CONVENTIONS { get; set; }
        public virtual DbSet<DEPOSITS_ALLFUNDS> DEPOSITS_ALLFUNDS { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<ec_groups> ec_groups { get; set; }
        public virtual DbSet<FORWARD_CONTRACTS_ALLFUNDS> FORWARD_CONTRACTS_ALLFUNDS { get; set; }
        public virtual DbSet<GENERAL_LEDGER> GENERAL_LEDGER { get; set; }
        public virtual DbSet<INVESTMENT_TYPES> INVESTMENT_TYPES { get; set; }
        public virtual DbSet<INVESTOR_TRANSFERS> INVESTOR_TRANSFERS { get; set; }
        public virtual DbSet<INVESTORS_DEALS> INVESTORS_DEALS { get; set; }
        public virtual DbSet<INVESTORS_DEALS_SCHRODERS> INVESTORS_DEALS_SCHRODERS { get; set; }
        public virtual DbSet<INVESTORS_FUNDS> INVESTORS_FUNDS { get; set; }
        public virtual DbSet<MONEYTRANSFER_TYPE> MONEYTRANSFER_TYPE { get; set; }
        public virtual DbSet<MUNICIPALITY> MUNICIPALITY { get; set; }
        public virtual DbSet<NAV_CALCULATION_ALLFUNDS> NAV_CALCULATION_ALLFUNDS { get; set; }
        public virtual DbSet<NAV_FUNDS> NAV_FUNDS { get; set; }
        public virtual DbSet<NOM_BANKS> NOM_BANKS { get; set; }
        public virtual DbSet<ORDERS_INPUT> ORDERS_INPUT { get; set; }
        public virtual DbSet<ORDERS_INPUT_SCHRODERS> ORDERS_INPUT_SCHRODERS { get; set; }
        public virtual DbSet<ORDERS_OPERATIONS> ORDERS_OPERATIONS { get; set; }
        public virtual DbSet<ORGANIZATIONS> ORGANIZATIONS { get; set; }
        public virtual DbSet<PORTFOLIO_DEALS> PORTFOLIO_DEALS { get; set; }
        public virtual DbSet<PORTFOLIO_ORDERS> PORTFOLIO_ORDERS { get; set; }
        public virtual DbSet<PORTFOLIO_SUMMARY_FUNDS> PORTFOLIO_SUMMARY_FUNDS { get; set; }
        public virtual DbSet<PORTFOLIO_SUMMARY_FUNDS_SCH> PORTFOLIO_SUMMARY_FUNDS_SCH { get; set; }
        public virtual DbSet<PORTFOLIOOPERATIONS_TYPE> PORTFOLIOOPERATIONS_TYPE { get; set; }
        public virtual DbSet<PORTFOLIOORDERS_TYPE> PORTFOLIOORDERS_TYPE { get; set; }
        public virtual DbSet<POSITIONS_INVESTMENTS> POSITIONS_INVESTMENTS { get; set; }
        public virtual DbSet<RM_PRICES> RM_PRICES { get; set; }
        public virtual DbSet<SUMARY_NAV_FUNDS> SUMARY_NAV_FUNDS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblEmployees> tblEmployees { get; set; }
        public virtual DbSet<TEST_PRICES> TEST_PRICES { get; set; }
        public virtual DbSet<TOWNS> TOWNS { get; set; }
        public virtual DbSet<TYPES> TYPES { get; set; }
        public virtual DbSet<UD_FUNDS> UD_FUNDS { get; set; }
        public virtual DbSet<UD_FUNDS_schroders> UD_FUNDS_schroders { get; set; }
        public virtual DbSet<usd_histrates> usd_histrates { get; set; }
        public virtual DbSet<VN> VN { get; set; }
        public virtual DbSet<acc_test> acc_test { get; set; }
        public virtual DbSet<BIG_ACCOUNTING_TABLE_HIST> BIG_ACCOUNTING_TABLE_HIST { get; set; }
        public virtual DbSet<CD_MESSAGES_HIST> CD_MESSAGES_HIST { get; set; }
        public virtual DbSet<CD_TEXT_MESSAGES_HIST> CD_TEXT_MESSAGES_HIST { get; set; }
        public virtual DbSet<contracts_schroders_HIST> contracts_schroders_HIST { get; set; }
        public virtual DbSet<DAILYPRICES_HIST> DAILYPRICES_HIST { get; set; }
        public virtual DbSet<db_beta> db_beta { get; set; }
        public virtual DbSet<INVESTORS_DEALS_HIST> INVESTORS_DEALS_HIST { get; set; }
        public virtual DbSet<INVESTORS_DEALS_SCHRODERS_HIST> INVESTORS_DEALS_SCHRODERS_HIST { get; set; }
        public virtual DbSet<INVESTORS_FUNDS_HIST> INVESTORS_FUNDS_HIST { get; set; }
        public virtual DbSet<ORDERS_INPUT_HIST> ORDERS_INPUT_HIST { get; set; }
        public virtual DbSet<ORDERS_INPUT_SCHRODERS_HIST> ORDERS_INPUT_SCHRODERS_HIST { get; set; }
        public virtual DbSet<PORTFOLIO_DEALS_HIST> PORTFOLIO_DEALS_HIST { get; set; }
        public virtual DbSet<PORTFOLIO_ORDERS_HIST> PORTFOLIO_ORDERS_HIST { get; set; }
        public virtual DbSet<PORTFOLIO_SUMMARY_FUNDS_HIST> PORTFOLIO_SUMMARY_FUNDS_HIST { get; set; }
        public virtual DbSet<PORTFOLIO_SUMMARY_FUNDS_SCH_HIST> PORTFOLIO_SUMMARY_FUNDS_SCH_HIST { get; set; }
        public virtual DbSet<RM_PRICES_HIST> RM_PRICES_HIST { get; set; }
        public virtual DbSet<SUMARY_NAV_FUNDS_HIST> SUMARY_NAV_FUNDS_HIST { get; set; }
        public virtual DbSet<TEST_CD_MESSAGES> TEST_CD_MESSAGES { get; set; }
        public virtual DbSet<TEST_CD_TEXT_MESSAGES> TEST_CD_TEXT_MESSAGES { get; set; }
        public virtual DbSet<VN_HIST> VN_HIST { get; set; }
    }
}
