//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS_INPUT
    {
        public double ORDER_ID { get; set; }
        public Nullable<double> ORDER_ID_STRING { get; set; }
        public string AUTHORISED1 { get; set; }
        public string AUTHORISED2 { get; set; }
        public Nullable<System.DateTime> DATE_DEAL { get; set; }
        public Nullable<System.DateTime> DATE_PRICE { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string EMPLOYE { get; set; }
        public string EXECUTION_TYPE { get; set; }
        public string INVESTOR { get; set; }
        public string INVESTOR_ID { get; set; }
        public string MONEY_BANK { get; set; }
        public string MONEY_BEN { get; set; }
        public string MONEY_BIC { get; set; }
        public string MONEY_IBAN { get; set; }
        public string MONEY_RECEIVED { get; set; }
        public Nullable<double> OLD_ID { get; set; }
        public string ORD_TIME { get; set; }
        public string ORDER_CURRENCY { get; set; }
        public string ORDER_FUND { get; set; }
        public string ORDER_PLACE { get; set; }
        public Nullable<double> ORDER_SHARES { get; set; }
        public Nullable<double> ORDER_SUM { get; set; }
        public string ORDER_TYPE { get; set; }
        public string PLACE_EXECUTION { get; set; }
        public string PMNT_DETAILS { get; set; }
        public Nullable<double> REFFERENCE_AMOUNT2 { get; set; }
        public string STATUS { get; set; }
        public string TRANSFER_TYPE_CD { get; set; }
        public string VALIDITY { get; set; }
        public Nullable<double> VN_NUMBER { get; set; }
        public string user_modified { get; set; }
        public string user_modified_time { get; set; }
        public string ORDER_ACCOUNTED { get; set; }
    }
}
