//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_PRICES_HIST
    {
        public System.DateTime rmdate { get; set; }
        public string rmticker { get; set; }
        public Nullable<double> rmopen { get; set; }
        public Nullable<double> rmlow { get; set; }
        public Nullable<double> rmhigh { get; set; }
        public Nullable<double> rmclose { get; set; }
        public Nullable<double> rmadjclose { get; set; }
        public Nullable<double> rmvolume { get; set; }
        public Nullable<double> par { get; set; }
        public string rm_mkt { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string USER_ID { get; set; }
        public string ACT_EVENT { get; set; }
    }
}
