//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployees
    {
        public int lngEmpID { get; set; }
        public string strEmpName { get; set; }
        public string strEmpPassword { get; set; }
        public string strAccess { get; set; }
        public string strName { get; set; }
        public string strTown { get; set; }
        public string strIndex { get; set; }
        public string EmpFunction { get; set; }
        public string emptown { get; set; }
    }
}
