//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_CD_TEXT_MESSAGES
    {
        public string CD_MID { get; set; }
        public string FIRSTLINE2 { get; set; }
        public string SECONDLINE2 { get; set; }
        public string THIRDLINE2 { get; set; }
        public string FOURTHLINE2 { get; set; }
        public string FIFTHLINE2 { get; set; }
        public string SIXTHLINE2 { get; set; }
        public string SEVENTHLINE2 { get; set; }
        public string EIGHTHLINE2 { get; set; }
        public string NINETHLINE2 { get; set; }
        public string TENTHLINE2 { get; set; }
        public string ELEVENTHLINE2 { get; set; }
        public string TWELVTHLINE2 { get; set; }
        public string THIRTEENTHLINE2 { get; set; }
        public string FOURTEENTHLINE2 { get; set; }
        public string FIFTEENTHLINE2 { get; set; }
        public string SIXTEENTHLINE2 { get; set; }
        public string SEVENTEENTHLINE2 { get; set; }
        public string EIGHTEENTHLINE2 { get; set; }
        public string NINETEENTHLINE2 { get; set; }
        public string TWTENTIETHLINE2 { get; set; }
        public string TWENTYFIRSTLINE2 { get; set; }
        public string TWENTYSECONDLINE2 { get; set; }
        public string TWENTYTHIRDLINE2 { get; set; }
        public string TWENTYFOURTHLINE2 { get; set; }
        public string TWENTYFIFTHLINE2 { get; set; }
        public string TWETTYSIXTHLINE2 { get; set; }
        public string TWETTYSEVENTHLINE2 { get; set; }
        public string TWENTYEIGTHLINE2 { get; set; }
        public string TWENTYNINGHTLINE2 { get; set; }
    }
}
