//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_PRICES
    {
        public System.DateTime MYDATE { get; set; }
        public string POSITION1 { get; set; }
        public Nullable<double> MYPRICE1 { get; set; }
        public Nullable<double> MYCHANGE1 { get; set; }
        public Nullable<double> LOGCHANGE1 { get; set; }
        public Nullable<double> VOLUME1 { get; set; }
    }
}
