//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_FUNDS_schroders
    {
        public int FUND_ID { get; set; }
        public string ISINCODE { get; set; }
        public string FUNDNAME { get; set; }
        public string FUNDCURRENCY { get; set; }
        public string FUND_type { get; set; }
        public string MANAGEMENTCOMPANY { get; set; }
        public string FUND_TICKER { get; set; }
        public string FUND_INT_CODE { get; set; }
        public Nullable<double> ENTRY_FEE { get; set; }
        public string BANK { get; set; }
        public string BIC { get; set; }
        public string FUND_CLASS { get; set; }
        public string ACC_DISTR { get; set; }
        public string HEDGED { get; set; }
    }
}
