//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VN
    {
        public int VN_ID { get; set; }
        public Nullable<System.DateTime> VN_DATE { get; set; }
        public Nullable<double> VN_STRING { get; set; }
        public string VN_ORD { get; set; }
        public string VN_PLACE { get; set; }
        public string VN_CLIENTID { get; set; }
        public string VN_EGN { get; set; }
        public string VN_NAME { get; set; }
        public string VN_CCY { get; set; }
        public Nullable<double> VN_AMOUNT { get; set; }
        public string VN_FUND { get; set; }
    }
}
