
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class BRANCH_BG
{

    public Nullable<int> BRANCH_ID { get; set; }

    public string BRANCH_BG1 { get; set; }

    public string BRANCH_ENG { get; set; }

}

}
