
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class BULLETIN_BFB
{

    public System.DateTime ДАТА_БЮЛЕТИН { get; set; }

    public string БОРСОВ_КОД { get; set; }

    public string НАИМЕНОВАНИЕ { get; set; }

    public Nullable<double> НОМИНАЛ { get; set; }

    public string ВАЛУТА { get; set; }

    public Nullable<System.DateTime> ДАТА_ДИВИДЕНТ { get; set; }

    public Nullable<double> ДИВИДЕНТ { get; set; }

    public Nullable<double> ПРОЦЕНТ_ОТ_НОМИНАЛ { get; set; }

    public Nullable<double> ЦЕНА_ОТВАРЯНЕ { get; set; }

    public Nullable<System.DateTime> ДАТА_ЦЕНА_ОТВАРЯНЕ { get; set; }

    public Nullable<double> ПОСЛЕДНА_ЦЕНА { get; set; }

    public Nullable<double> ОБЕМ_АКЦИИ { get; set; }

    public Nullable<double> НАЙ_ВИСОКА_ЦЕНА { get; set; }

    public Nullable<double> НАЙ_НИСКА_ЦЕНА { get; set; }

    public Nullable<double> ПОСЛЕДНА_ЦЕНА2 { get; set; }

    public Nullable<double> ПРОМЯНА { get; set; }

    public Nullable<double> СРЕДНА_ЦЕНА { get; set; }

    public Nullable<double> ЦЕНА_ПРОДАВА { get; set; }

    public Nullable<double> ОБЕМ_ПРОДАВА { get; set; }

    public Nullable<double> ЦЕНА_КУПУВА { get; set; }

    public Nullable<double> ОБЕМ_КУПУВА { get; set; }

    public string ПАЗАРЕН_СЕГМЕНТ { get; set; }

    public Nullable<int> INDEX { get; set; }

    public string FUND { get; set; }

}

}
