
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class contracts_kcm
{

    public int contract_kcm_id { get; set; }

    public Nullable<System.DateTime> contract_kcm_date { get; set; }

    public string contract_kcm_time { get; set; }

    public string contract_kcm_place { get; set; }

    public string contract_kcm_client { get; set; }

    public string contract_kcm_iban { get; set; }

    public string contract_kcm_bank { get; set; }

    public string contract_kcm_pylnom1 { get; set; }

    public string contract_kcm_pylnom2 { get; set; }

    public string contract_kcm_crby { get; set; }

    public string contract_kcm_crwhen { get; set; }

    public string contract_kcm_modby { get; set; }

    public string contract_kcm_modwhen { get; set; }

}

}
