
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class DAILYPRICES
{

    public System.DateTime DATE { get; set; }

    public string MARKET { get; set; }

    public string POSITION { get; set; }

    public string CURRENCY { get; set; }

    public Nullable<double> LAST_PRICE { get; set; }

    public Nullable<System.DateTime> DATE_LAST_PRICE { get; set; }

    public Nullable<double> QUANTITY_TRADED { get; set; }

    public Nullable<double> BEST_BID { get; set; }

    public Nullable<double> QUANTIY_BEST_BID { get; set; }

    public Nullable<double> BEST_ASK { get; set; }

    public Nullable<double> QUANTITY_BEST_ASK { get; set; }

    public Nullable<double> AVERAGE_PRICE { get; set; }

    public Nullable<double> OTHERPRICE { get; set; }

    public string DES_OTHERPRICE { get; set; }

    public Nullable<double> OPEN { get; set; }

    public Nullable<double> HIGH { get; set; }

    public Nullable<double> LOW { get; set; }

    public Nullable<double> NUMBER_OF_TRADES { get; set; }

    public Nullable<int> INDEX { get; set; }

    public Nullable<double> PAR { get; set; }

    public string FUND { get; set; }

}

}
