
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class db_beta
{

    public System.DateTime bdte { get; set; }

    public string bticker { get; set; }

    public Nullable<double> beta_sp { get; set; }

    public Nullable<double> beta_djubs { get; set; }

    public Nullable<double> beta_b1 { get; set; }

    public Nullable<double> beta_b2 { get; set; }

    public string beta_fund { get; set; }

}

}
