
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class INVESTORS_DEALS_FORMATED
{

    public Nullable<System.DateTime> DATE_DEAL { get; set; }

    public double DEALS_ID { get; set; }

    public Nullable<double> DEALS_ID_STRING { get; set; }

    public string DEALS_INVESTOR { get; set; }

    public string DEALS_INVESTOR_NAME { get; set; }

    public string DEALS_TYPE { get; set; }

    public string DEALS_FUND { get; set; }

    public string DEALS_CURRENCY { get; set; }

    public Nullable<double> NEW_SHARES { get; set; }

    public Nullable<double> DEALS_PRICE { get; set; }

    public Nullable<double> NEW_AMOUNT { get; set; }

}

}
