
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class INVESTOR_AUTH2
{

    public int AUTH_CLID2 { get; set; }

    public string AUTH_CLID_STRING2 { get; set; }

    public string AUTH_PERSONAL_ID2 { get; set; }

    public string AUTH_FULLNAME2 { get; set; }

    public string AUTH_PID2 { get; set; }

    public string AUTH_COUNTRY2 { get; set; }

    public string AUTH_TOWN2 { get; set; }

    public string AUTH_ADDRESS2 { get; set; }

    public string AUTH_TYPE2 { get; set; }

    public string AUTH_DOC2 { get; set; }

    public string AUTH_DATE2 { get; set; }

    public string AUTH_PID_ISSUEDBY2 { get; set; }

    public string AUTH_PID_DATE2 { get; set; }

    public string AUTH_NOTARY2 { get; set; }

    public string AUTH_TEL_MOBILE2 { get; set; }

    public string AUTH_EMAIL2 { get; set; }

}

}
