//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTFOLIODEALS_ANYFUND
    {
        public double PORT_DEAL_ID { get; set; }
        public Nullable<double> PORT_DEALORD_ID { get; set; }
        public string PORT_DEAL_FUND { get; set; }
        public Nullable<System.DateTime> PORT_DEAL_TRADEDATE { get; set; }
        public Nullable<System.DateTime> PORT_DEAL_SETTLDATE { get; set; }
        public string PORT_DEAL_INV { get; set; }
        public string PORT_DEAL_CCY { get; set; }
        public string PORT_DEAL_TYPE { get; set; }
        public Nullable<int> PORT_DEAL_QUANT { get; set; }
        public Nullable<double> PORT_DEAL_PRICE { get; set; }
        public Nullable<double> PER_NOMINAL { get; set; }
        public Nullable<double> OTHERCOMMISSION { get; set; }
        public Nullable<double> BROKERCOMMISSION { get; set; }
        public Nullable<double> PORT_DEAL_AMOUNT { get; set; }
        public string PORT_DEAL_BROKER { get; set; }
        public Nullable<double> PORT_DEAL_FX { get; set; }
        public Nullable<System.DateTime> PORT_DEAL_ACTUALSETTLDATE { get; set; }
        public string CONFIRMATION { get; set; }
        public Nullable<int> NEW_QUANTITY { get; set; }
    }
}
