
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fima.Data.DbModels
{

using System;
    using System.Collections.Generic;
    
public partial class RESERVE_SUMMARY
{

    public string TRANSACTION_ISIN { get; set; }

    public string TRANSACTION_CCY { get; set; }

    public string TRANSACTION_DES { get; set; }

    public string TRANSACTION_FUNDID { get; set; }

    public double TRANSACTION_ACCOUNT { get; set; }

    public Nullable<double> TOTAL_Q { get; set; }

    public Nullable<double> TOTAL_SUM { get; set; }

    public Nullable<double> TOTAL_SUMBGN { get; set; }

}

}
