//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fima.Data.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UD_FUNDS
    {
        public string FUND_ID { get; set; }
        public string FUNDNAME { get; set; }
        public string FUNDCURRENCY { get; set; }
        public string BULSTAT { get; set; }
        public string ADDDRESS_COUNTRY { get; set; }
        public string ADDRESS_TOWN { get; set; }
        public string ADDRESS { get; set; }
        public string ISINCODE { get; set; }
        public string STOCK_TYPE { get; set; }
        public string MANAGEMENTCOMPANY { get; set; }
        public string LICENCE_FSC { get; set; }
        public string ACCOUNT_WITH_CD { get; set; }
        public string CD_ID { get; set; }
        public string FUND_TICKER { get; set; }
        public Nullable<double> UD_RENUM { get; set; }
        public Nullable<double> RENUM_DAYS { get; set; }
        public string ESCROW1 { get; set; }
        public string ESCROW1_CCY { get; set; }
        public string ESCROW2 { get; set; }
        public string ESCROW2_CCY { get; set; }
        public string UD_TYPE { get; set; }
        public string COBOS_ID { get; set; }
        public string BANK { get; set; }
        public string BIC { get; set; }
        public string CD_IBAN { get; set; }
    }
}
